#! /bin/bash
#$ -cwd
#$ -l h_vmem=50g
#$ -l h_rt=12:00:00

'''
# Author: Tamara Ouspenskaia
# Date: 01/14/2020
# Objective: This script outputs the read coverage for variant sites
'''



# Inputs:

BAM=$1
ANNOT=$2  # ORFs.variants.annot generated by variant_pipeline.sh
ANALYSIS=$3 # snvs.analysis.tab generated by variant_pipeline.sh
OUT_DIR=$4

mkdir -p $OUT_DIR

cd $OUT_DIR

# BAM file needs to be sorted and indexed

#samtools index $BAM

python ../snv_coverage.py \
--bam $BAM \
--mut_annot $ANNOT \
--analysis_tab $ANALYSIS \
--read_counts $OUT_DIR/"snvs.read_counts.txt" \
--over3_all $OUT_DIR/"over3reads_orfs_all.txt" \
--over3_pass $OUT_DIR/"over3reads_orfs_pass.txt"

#qsub ../snv_coverage.sh /path/to/STAR/file_Aligned.sortedByCoord.out.bam /path/to/ORFs.variants.annot /path/to/snvs.analysis.tab /path/to/output
